service: src-service
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "dev"
  region: "ap-south-1"
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "Content-Type"
        - "Authorization"
        - "accesstoken"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
    authorizers:
      adminAuthorizer:
        type: request
        functionArn: ${env:ADMIN_AUTHORIZER_ARN}
  timeout: 30

functions: 
  AddNotification:
    handler: src/handler.AddNotification
    events:
      - httpApi:
          path: /web/addNotification
          method: post
          authorizer: adminAuthorizer
  
  GetAllNotificationList:
    handler: src/handler.GetAllNotificationList
    events:
      - httpApi:
          path: /web/getAllNotificationList
          method: post
          authorizer: adminAuthorizer

  ViewNotificationById:
    handler: src/handler.ViewNotificationById
    events:
      - httpApi:
          path: /web/viewNotificationById
          method: post
          authorizer: adminAuthorizer
  
  EditNotification:
    handler: src/handler.EditNotification
    events:
      - httpApi:
          path: /web/editNotification
          method: post
          authorizer: adminAuthorizer

  CreateEmailTemplate:
    handler: src/handler.CreateEmailTemplate
    events:
      - httpApi:
          path: /web/createEmailTemplate
          method: post
          authorizer: adminAuthorizer
  
  UpdateEmailTemplate:
    handler: src/handler.UpdateEmailTemplate
    events:
      - httpApi:
          path: /web/updateEmailTemplate
          method: post
          authorizer: adminAuthorizer
  
  GetAllEmailTemplates:
    handler: src/handler.GetAllEmailTemplates
    events:
      - httpApi:
          path: /web/getAllEmailTemplates
          method: post
          authorizer: adminAuthorizer
  
  GetEmailTemplateByMailKey:
    handler: src/handler.GetEmailTemplateByMailKey
    events:
      - httpApi:
          path: /web/getEmailTemplateByMailKey
          method: post
          authorizer: adminAuthorizer
  
  GetEmailTemplateById:
    handler: src/handler.GetEmailTemplateById
    events:
      - httpApi:
          path: /web/getEmailTemplateById
          method: post
          authorizer: adminAuthorizer
  
  UpdateEmailTemplateStatus:
    handler: src/handler.UpdateEmailTemplateStatus
    events:
      - httpApi:
          path: /web/updateEmailTemplateStatus
          method: post
          authorizer: adminAuthorizer

package:
  individually: true
  include:
    - package.json
  exclude:
    - node_modules/**
    - tests/**
    - .git/**
    - logs/**
    - docs/**
    - .gitignore
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
    - env/**
    - package-lock.json
    - serverless.yml

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-prune-plugin
  - serverless-package-external
  - serverless-dotenv-plugin
